apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: default
spec:
  ports:
  - port: 9200
    targetPort: 9200
  selector:
    app: elasticsearch
  type: ClusterIP  # or NodePort if you want to expose it outside the cluster
